### ISSUE TITLE
Issue loading Torch-converted weights to torch-borzoi model (missing keys)

### ISSUE THREAD

**Issue by sdisorbo** [johahi/borzoi-pytorch#2]
In `pytorch_borzoi_example_eqtl_chr10_116952944_T_C.ipynb`, when I load the converted torch weights into the model, I see this missing keys error: 
`Missing key(s) in state_dict: "transformer.8.0.fn.0.weight", "transformer.8.0.fn.0.bias", "transformer.8.0.fn.1.rel_content_bias", "transformer.8.0.fn.1.rel_pos_bias", "transformer.8.0.fn.1.to_q.weight", "transformer.8.0.fn.1.to_k.weight", "transformer.8.0.fn.1.to_v.weight", "transformer.8.0.fn.1.to_out.weight", "transformer.8.0.fn.1.to_out.bias", "transformer.8.0.fn.1.to_rel_k.weight", "transformer.8.1.fn.0.weight", "transformer.8.1.fn.0.bias".`

Originally noticed there were way more transformer blocks in the pre-published tensorflow model, so we increased the range in the transformer loop in` pytorch_borzoi_model.py` as shown below: 
```

transformer = []
        for _ in range(8):
            transformer.append(nn.Sequential(
               ....
               ....
)
```
This resulted in the error presented at the beginning of the issue, where we have missing keys in the torch transformer blocks.

**Comment by johahi** [comment]
Hi Sam, the TF model only has 8 transformer layers (see pre-print supp information and [here](https://github.com/calico/borzoi/blob/main/examples/params_pred.json)), can you share where you are getting this from? Note that each call of seqnn.SeqNN(params_model) increments the layernames/transformer layer numbers (see new cell in the weight conversion notebook where I added an assertion).

**Comment by sdisorbo** [comment]
We had differing models of TF which I believe was throwing us off--resolved, thank you!
