### ISSUE TITLE
Mouse model

### ISSUE THREAD

**Issue by luciabarb** [johahi/borzoi-pytorch#5]
Hi! 

Do you plan to include the mouse heads as well?

Thank you!

**Comment by johahi** [comment]
Hi Lucia, I'll try to upload the mouse heads some time next week, when I converted the weights last year, they were not online. Will let you know once I uploaded them :)

**Comment by luciabarb** [comment]
Amazing, thanks Johannes :)

**Comment by johahi** [comment]
I uploaded them, so after updating the package, you should be able to load the mouse replicates with `Borzoi.from_pretrained('johahi/borzoi-replicate-0-mouse')`.
For now, one has to add `is_human =False` in the forward, else it'll throw an error that the human head does not exist. I'll see if I have a nicer solution for this soon. I expected the weights for both both `replicate-0-human`, and `replicate-0-mouse` to be the same except for the heads, but this seems not to be the case - odd...
